#!/usr/bin/python3
import sys

if __name__ == "__main__":

    argument = 0
    len_o_av = len(sys.argv)- 1
    
    if len_o_av == 0:
        argument = 0
        print("{} arguments.".format(argument))

    elif len_o_av == 1:
        for i in range(len_o_av):
            argument += 1
            print("{} argument:".format(argument))
            print("{}: ".format(i), sys.argv[i])


