#!/usr/bin/node

const first = process.argv[2];
const result = parseInt(first, 10);

// check if input is Not a Number or else
if (isNaN(result)) {
  console.log('Missing size');
} else {
  for (let i = 0; i < result; i++) {
    // create a string to contain your concat strings
    let ask = '';

    for (let j = 0; j < result; j++) {
      ask += 'x' + ' ';
    }
    console.log(ask);
  }
}
